AWSTemplateFormatVersion: 2010-09-09
Description: Driver template to deploy VPC
Parameters:
  project:
    Type: String
    Description: Project Name
    Default: cloudweb
  env:
    Type: String
    AllowedValues: [prod, dev, qa]
    Description: Environment Name
    Default: dev
  s3ArtifactPath:
    Type: String
    Default: "https://cloudweb-dev-us-east-1-7123456789.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        project: !Ref project
        env: !Ref env
        vpcCidr: 10.0.0.0/16
        publicSubnet1Cidr: 10.0.1.0/24
        publicSubnet2Cidr: 10.0.2.0/24
        privateSubnet1Cidr: 10.0.3.0/24
        privateSubnet2Cidr: 10.0.4.0/24
        publicSubnet3Cidr: 10.0.36.0/24
        publicSubnet4Cidr: 10.0.37.0/24
        publicIPActive: True
        vpcDnsEnabled: True
        vpcDnsSupport: True
      TemplateURL: !Sub "${s3ArtifactPath}/vpc/vpc-app.yml"

Outputs:
  vpcId:
    Value: !Ref vpc
    Export:
      Name: !Sub "${project}-${env}-vpc-${AWS::Region}"
